# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    machine:

    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
     - checkout
     - setup_remote_docker

     # build the application image
     - run: docker build -t jira-board:$CIRCLE_SHA1 .
     - run: sudo apt install python-pip python2.7-dev
     - run: sudo pip install awscli
     - run: bash ./deploy.sh
     # - run: aws ecr get-login --no-include-email --region eu-west-1 | sh
     # - run: docker tag jira-board:latest 192167080104.dkr.ecr.eu-west-1.amazonaws.com/jira-board:latest
     # - run: docker push 192167080104.dkr.ecr.eu-west-1.amazonaws.com/jira-board:latest
     # - run: aws ecs update-service --cluster jira --service jira-service